### PR TITLE
Release of v10.4.3

### PR DESCRIPTION
**Pull request by Frzk**
Related to #78 
Tested here: https://grafana.osc-st-fr1.st-sc.fr/

Please double-check it's working as expected :)

Notes:
- I had to update the `Procfile` to avoid a warning (`grafana-server is deprecated in favor of `grafana server`)
- I also had to update the `GF_DATABASE_URL` to set `sslmode` to `require` (`prefer` is not supported anymore)

### CODE REVIEW

**Comment by Frzk** [comment]
I guess I should also update the `scalingo.json` file to update the `GF_DATABASE_URL`.
I'm wondering if I should leave it with an empty value (or instructions) or I should get rid of it?

**Review by EtienneM — APPROVED** [review]
> I'm wondering if I should leave it with an empty value (or instructions) or I should get rid of it?

In this case, the `scalingo.json` is used for one-click deploy. I think you should leave it with an empty value.

**Review by EtienneM — APPROVED** [review]

**Review by brandon-welsch — APPROVED** [review]
LGTM

**Review by brandon-welsch — APPROVED** [review]
LGTM

**Pull request merged**
